//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaotitosFoodtruck.Src.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedioEnvio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MedioEnvio()
        {
            this.Pedido = new HashSet<Pedido>();
        }
    
        public int ID { get; set; }
        public string NombreChofer { get; set; }
        public string CelularChofer { get; set; }
        public Nullable<int> TipoVehiculoID { get; set; }
    
        public virtual TipoVehiculo TipoVehiculo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pedido> Pedido { get; set; }
    }
}
