//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaotitosFoodtruck.Src.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pedido()
        {
            this.TacoIngrediente = new HashSet<TacoIngrediente>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ClienteID { get; set; }
        public Nullable<int> MedioEnvioID { get; set; }
        public Nullable<int> MedioDePagoID { get; set; }
        public Nullable<System.DateTime> Fecha_Hora { get; set; }
        public Nullable<decimal> ImporteTotal { get; set; }
        public Nullable<bool> Entregado { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual MedioDePago MedioDePago { get; set; }
        public virtual MedioEnvio MedioEnvio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TacoIngrediente> TacoIngrediente { get; set; }
    }
}
