//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaotitosFoodtruck.Src.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TacotitoDosEntities : DbContext
    {
        public TacotitoDosEntities()
            : base("name=TacotitoDosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Ingrediente> Ingrediente { get; set; }
        public virtual DbSet<MedioDePago> MedioDePago { get; set; }
        public virtual DbSet<MedioEnvio> MedioEnvio { get; set; }
        public virtual DbSet<Pedido> Pedido { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Taco> Taco { get; set; }
        public virtual DbSet<TacoIngrediente> TacoIngrediente { get; set; }
        public virtual DbSet<TipoIngrediente> TipoIngrediente { get; set; }
        public virtual DbSet<TipoVehiculo> TipoVehiculo { get; set; }
    }
}
